version: "3.3"

services:
  backend:
    image: "backend-local"
    build: .
    container_name: backend
    stdin_open: true
    tty: true
    env_file:
      - .env

  memcached:
    image: memcached
    container_name: memcached

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    env_file:
      - .env
