version: "3.3"

services:
  backend:
    image: "backend-local"
    build: .
    container_name: backend
    stdin_open: true
    tty: true
    env_file:
      - .env

  celery:
    image: "backend-local"
    command: celery -A settings worker -l info --pidfile=/tmp/celery.pid
    build: .
    container_name: celery
    stdin_open: true
    tty: true
    env_file:
      - .env

  flower:
    image: "backend-local"
    command: celery flower -A tasks
    build: .
    container_name: flower
    stdin_open: true
    tty: true

  celerybeat:
    image: "backend-local"
    command: celery -A settings beat -l info --schedule=/tmp/celerybeat-schedule --pidfile=/tmp/celerybeat.pid
    build: .
    container_name: celerybeat
    stdin_open: true
    tty: true
    env_file:
      - .env

  memcached:
    image: memcached
    container_name: memcached

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    env_file:
      - .env

  nginx:
    image: nginx:1.19
    container_name: "nginx"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      #- "8080:8080"  # windows specific!!!
      - "80:80"
      - "443:443"

  portainer:
    image: portainer/portainer-ce
    container_name: "portainer"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/home/stx/data"
    ports:
      - "8080:8080"
      - "9000:9000"
