version: "3.3"

services:
#  backend:
#    command: python app/manage.py runserver 0:8000
#    volumes:
#      - "./:/home/build"
#    ports:
#      - "8000:8000"
#      - "8001:8001"

  flower:
    ports:
      - "5555:5555"

  memcached:
    ports:
      - "11211:11211"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:13.4-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data_django:/var/lib/postgresql/data

  pgadmin_dj:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:5.6
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "5050:5050"

volumes:
  db_data_django: {}
  portainer_data:
    external: true

