RATE_TYPE_USD = 0  # 'USD'
RATE_TYPE_EUR = 1  # 'EUR'

RATE_TYPE_CHOICES = (
    (RATE_TYPE_USD, 'Dollar'),
    (RATE_TYPE_EUR, 'Euro'),
)

REQUEST_METHOD_GET = 0
REQUEST_METHOD_POST = 1

REQUEST_METHOD_CHOICES = (
    (REQUEST_METHOD_GET, 'GET'),
    (REQUEST_METHOD_POST, 'POST'),
)
