# Generated by Django 3.2.3 on 2021-06-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('url', models.URLField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=30)),
            ],
        ),
    ]
