# Generated by Django 3.2.3 on 2021-07-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_contactus_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='type_curr_new',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Dollar'), (1, 'Euro')], default=100),
        ),
    ]
