# Generated by Django 3.2.3 on 2021-07-11 20:48

from django.db import migrations


def forwards(apps, schema_editor):
    Rate = apps.get_model('currency', 'Rate')
    for rate in Rate.objects.all():
        rate.type_curr_new = 1 if 'eur' in rate.type_curr else 0
        rate.save()


def backwards(apps, schema_editor):
    print('HELLO FROM BACKWARDS')


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_rate_type_curr_new'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
