# Generated by Django 3.2.3 on 2021-07-11 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_auto_20210711_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='type_curr',
        ),
    ]
