# Generated by Django 3.2.3 on 2021-07-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_auto_20210711_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('counter', models.PositiveBigIntegerField()),
                ('request_method', models.PositiveSmallIntegerField(choices=[(0, 'GET'), (1, 'POST')])),
                ('status_code', models.CharField(max_length=3)),
            ],
        ),
    ]
