# Generated by Django 3.2.3 on 2021-07-13 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_analyticslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='created',
        ),
        migrations.AddField(
            model_name='bank',
            name='original_url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='bank',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.bank'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='bank',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name='analyticslog',
            unique_together={('path', 'status_code'), ('path', 'request_method')},
        ),
    ]
