# Generated by Django 3.2.3 on 2021-07-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0011_auto_20210713_2144'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analyticslog',
            unique_together={('path', 'request_method')},
        ),
    ]
