# Generated by Django 3.2.3 on 2021-07-13 23:29

from django.db import migrations


def forwards(apps, schema_editor):
    Rate = apps.get_model('currency', 'Rate')
    Bank = apps.get_model('currency', 'Bank')

    privatbank = Bank.objects.create(
        name='PrivatBank',
        url='https://api.privatbank.ua/p24api/pubinfo?json&exchange&coursid=5',
        original_url='https://privatbank.ua/ru',
        number='3700',
    )

    for rate in Rate.objects.all():
        if 'privatbank' in rate.source.lower():
            rate.bank = privatbank
        rate.save()


def backwards(apps, schema_editor):
    print('HELLO FROM BACKWARDS')


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0011_auto_20210714_0207'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
