# Generated by Django 3.2.3 on 2021-07-13 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0012_auto_20210713_2329'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analyticslog',
            unique_together={('path', 'status_code')},
        ),
    ]
