# Generated by Django 3.2.3 on 2021-07-14 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0014_auto_20210714_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='source',
        ),
    ]
