# Generated by Django 3.2.3 on 2021-07-19 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0016_alter_bank_code_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='bank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='currency.bank'),
        ),
    ]
