# Generated by Django 3.2.3 on 2021-07-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0018_alter_rate_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_logo',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
