# Generated by Django 3.2.3 on 2021-08-03 19:50

import currency.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0019_bank_bank_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticslog',
            name='request_method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'GET'), (1, 'POST'), (2, 'PUT'), (3, 'PATCH'), (4, 'DELETE')]),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_logo',
            field=models.FileField(blank=True, default=None, null=True, upload_to=currency.models.bank_logo_directory_path),
        ),
        migrations.AlterField(
            model_name='rate',
            name='bank',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='currency.bank'),
        ),
    ]
