# Generated by Django 3.2.3 on 2021-08-08 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0020_auto_20210803_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='rate_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
