# Generated by Django 3.2.3 on 2021-08-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0021_rate_rate_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='rate_date',
            new_name='rate_dates',
        ),
    ]
